### PR TITLE
Parser improvements

### PR DESCRIPTION
**Pull request by jClugstor**
## Checklist

- [x ] Appropriate tests were added
- [x ] Any code changes were done in a way that does not break public API
- [ x] All documentation related to code changes were updated
- [ x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x ] Any new documentation only uses public API
  
## Additional context

This PR adds proper support for parsing in to an AST, and evaluating that AST to get a ModelingToolkit system. This means that the parsing no longer relies on parsing Julia expressions in to symbolics expression, adds proper support for all BaseModelica operators, etc. 

These changes were necessary to make implementing all of the BaseModelica specification possible in the future.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Precompilation failure?

**Comment by jClugstor** [comment]
Yeah, not sure why, looks like MTK can't precompile 
```
ERROR: LoadError: `unsorted_arguments(x)` is deprecated, use `arguments(x)` instead.
```

**Comment by ChrisRackauckas** [comment]
Can you isolate that depwarn?

**Comment by jClugstor** [comment]
Precompilation goes through now, but there's an Aqua error:
```
Aqua: Error During Test at /home/runner/work/BaseModelica.jl/BaseModelica.jl/test/qa.jl:2
  Got exception outside of a @test
  Failed to parse output of `detect_ambiguities`.
  The stdout was:
  
  
  The stderr was:
  WARNING: using deprecated binding SymbolicUtils.istree in Symbolics.
  , use iscall instead.
  Symbolics.istree is deprecated, use TermInterface.iscall instead.
```
It looks like it can't parse an error? 
I thought maybe the old version of `TermInterface` might be responsible for the depwarn, but if I try to update it, it downgrades many other packages, e.g. Symbolics, ModelingToolkit, etc.

**Comment by jClugstor** [comment]
Also this only happens when `--depwarn=error`

**Comment by ChrisRackauckas** [comment]
Turn the depwarn into an error locally and pinpoint the line of code causing it.

**Comment by jClugstor** [comment]
Yeah, did that, it doesn't point to anywhere except inside of Aqua, this is what happens when running `Aqua.test_ambiguities(BaseModelica, recursive = false)`
```
WARNING: using deprecated binding SymbolicUtils.istree in Symbolics.
, use iscall instead.
Symbolics.istree is deprecated, use TermInterface.iscall instead.
ERROR: use of deprecated variable: Symbolics.istree
Stacktrace:
 [1] all_methods(mods::Module; skip_deprecated::Bool)
   @ Aqua.Piracy ~/.julia/packages/Aqua/tHrmY/src/piracies.jl:42
 [2] all_methods
   @ ~/.julia/packages/Aqua/tHrmY/src/piracies.jl:21 [inlined]
 [3] #hunt#24
   @ ~/.julia/packages/Aqua/tHrmY/src/piracies.jl:193 [inlined]
 [4] hunt
   @ ~/.julia/packages/Aqua/tHrmY/src/piracies.jl:192 [inlined]
 [5] test_piracies(m::Module; broken::Bool, kwargs::@Kwargs{})
   @ Aqua ~/.julia/packages/Aqua/tHrmY/src/piracies.jl:218
 [6] test_piracies(m::Module)
   @ Aqua ~/.julia/packages/Aqua/tHrmY/src/piracies.jl:217
 [7] top-level scope
   @ REPL[15]:1
 [8] top-level scope
   @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1428
```
It happens in these three functions in the qa test set:
```
Aqua.test_ambiguities(BaseModelica, recursive = false)
Aqua.test_piracies(BaseModelica)
Aqua.test_unbound_args(BaseModelica)
```
But the error that it gives is 
```
 The stderr was:
  WARNING: using deprecated binding SymbolicUtils.istree in Symbolics.
  , use iscall instead.
  Symbolics.istree is deprecated, use TermInterface.iscall instead.
```
Which is the same warning I can get if I precompile MTK with `julia --depwarn=error`, it's a warning by the way, for some reason it doesn't error there. 

Maybe it's related to https://github.com/SciML/ModelingToolkit.jl/issues/2753 and https://github.com/JuliaSymbolics/Symbolics.jl/issues/1141 ? 

I'm just not sure since the errors don't point to specific lines, it's just saying that somewhere `istree` is being used.

**Comment by jClugstor** [comment]
```
 function ModelingToolkit.SymbolicUtils.istree(expr)
             throw(ErrorException("no istree"))
end
```
right?

This doesn't do anything if `--depwarn=yes` or `depwarn=no`, so it looks like it doesn't actually call `istree` anywhere.

And if `depwarn=error` is set, I can't override the function since using a deprecated variable is an error:
```
In [13]: function ModelingToolkit.SymbolicUtils.istree(expr)
             throw(ErrorException("no istree"))
         end
SymbolicUtils.istree is deprecated, use iscall instead.
ERROR: use of deprecated variable: SymbolicUtils.istree
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[13]:1
 [3] top-level scope
   @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1428
```

**Comment by ChrisRackauckas** [comment]
No, just go to that line of code that throws the warning and make it an error.

**Comment by jClugstor** [comment]
Sorry, I'm confused. I don't know where the warning is being thrown, I thought trying to find it was what I was doing by setting `depwarn=error`?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/d009ca8e986b12982dce13794218ea6b632da617/src/SymbolicUtils.jl#L23

**Comment by jClugstor** [comment]
I found that, but isn't that just where the deprecation is set? How would I turn using `istree` in to an error, isn't that what `depwarn=error` does? Wouldn't the warning be coming from wherever `istree` is called, which is what I want to find?

**Comment by ChrisRackauckas** [comment]
just delete that line. Make it impossible to get a deprecation

**Comment by jClugstor** [comment]
Oh yeah I tried that, all the tests pass with out any errors.

**Comment by jClugstor** [comment]
I know what's happening. Basically the ambiguities test for aqua creates a new Julia instance, and it uses `Base.julia_cmd()` to do it. So any options that were used to start the original Julia instance would be applied to it. 
```
# Ambiguity test is run inside a clean process.
    # https://github.com/JuliaLang/julia/issues/28804
    code = """
    $(Base.load_path_setup_code())
    using Aqua
    Aqua.test_ambiguities_impl(
        $packages_repr,
        $options_repr,
        $exclude_repr,
        $skipdetails,
    ) || exit(1)
    """
    cmd = Base.julia_cmd()
    if something(color, Base.JLOptions().color == 1)
        cmd = `$cmd --color=yes`
    end
    cmd = `$cmd --startup-file=no -e $code`
```
When I precompile MTK in a Julia session with `depwarn=error` I get a warning about how `istree` is deprecated, even though MTK doesn't use `istree` anymore. I get a warning, not an error. 

I think when Aqua gets to the point of `using ModelingToolkit` in BaseModelica, the `istree` warning is triggering an error.

**Comment by ChrisRackauckas** [comment]
Just throw a testset over the tests for now so it runs them all. See ModelingToolkit's test form for that.

**Comment by jClugstor** [comment]
They're all in testsets and safetestsets. Just the Aqua tests fail.

**Comment by ChrisRackauckas** [comment]
testset over that

**Comment by ChrisRackauckas** [comment]
Just do exactly as the ModelingToolkit docs...

**Comment by jClugstor** [comment]
Actions was down for a bit. Yeah, the `GROUP` stuff, right?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/ModelingToolkit.jl/blob/master/test/runtests.jl#L19

**Comment by jClugstor** [comment]
It decides to work now. Simply lovely

**Comment by ChrisRackauckas** [comment]
You're not running anything if you haven't set any test groups.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/ModelingToolkit.jl/blob/master/.github/workflows/ci.yml#L59-L62

**Comment by jClugstor** [comment]
Is that not what I did here? https://github.com/SciML/BaseModelica.jl/pull/22/commits/b85b7c2add479ec20a03b4fa7bf248e6994f981a#diff-f88e7ee60a80885f57e6c7794c2dd3d3604ffed08c7c2bde856b1669186e8444R32

**Comment by jClugstor** [comment]
It's actually running the tests now, I had to add `with:
      group: "${{ matrix.group }}"` to make sure it actually runs the groups :-|

**Comment by jClugstor** [comment]
Is it ok to merge this?

**Comment by ChrisRackauckas** [comment]
Run the formatter.

**Pull request merged**
